# main text of home
name: "Zontik Corporation"
description: |
  Landing Page for Zontik Corporation

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - "Rakefile"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "FAQ.md"
